#include "CANMetaData.h"
// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

CAN_RECV_ENTRY(BPS_TRIP, 1, true)
CAN_RECV_ENTRY(BPS_CONTACTOR_STATE, 1, true)
CAN_RECV_ENTRY(CONTROLS_FAULT, 1, true)
CAN_RECV_ENTRY(IO_STATE, 3, true)

// for CAN test, TODO: remove
CAN_RECV_ENTRY(0x001, 5, false)
CAN_RECV_ENTRY(0x002, 8, false)
CAN_RECV_ENTRY(0x003, 3, false)
CAN_RECV_ENTRY(0x004, 4, true)