#include "CANMetaData.h"
// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

CAN_RECV_ENTRY(BPS_TRIP, 1, true)
CAN_RECV_ENTRY(BPS_CONTACTOR_STATE, 1, true)
CAN_RECV_ENTRY(CONTROLS_FAULT, 1, true)
CAN_RECV_ENTRY(IO_STATE, 1, true)
